# symlinks for various dotfiles
# the target paths are all relative to the HOME directory
version = "1.0"

[[dotfiles]]
source = "dev/dotfiles/config/nightfox.yaml"
target = ".warp/themes/nightfox.yaml"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/forestfox.yaml"
target = ".warp/themes/forestfox.yaml"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/nord.yaml"
target = ".warp/themes/nord.yaml"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/starship.toml"
target = ".config/starship.toml"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/.zshrc"
target = ".config/zsh/.zshrc"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/.zshenv"
target = ".config/zsh/.zshenv"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/nvim"
target = ".config/nvim"
isFile = false

[[dotfiles]]
source = "dev/dotfiles/config/typioca.conf"
target = "./Library/Application Support/typioca/typioca.conf"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/config/ngrok.yml"
target = "./Library/Application Support/ngrok/ngrok.yml"
isFile = true

[[dotfiles]]
source = "dev/dotfiles/bin/netcoredbg"
target = "/usr/local/bin/netcoredbg"
isFile = false
